### ISSUE TITLE
cloud.rada.re down?

### ISSUE THREAD

**Issue by mehlon** [radare/radare.org#133]
The "try" link fails with a "Hmm. We’re having trouble finding that site." error for both http://cloud.radare.org/enyo and http://cloud.rada.re/enyo
This site says they're down too https://www.isitdownrightnow.com/cloud.rada.re.html

**Comment by radare** [comment]
Been down for 5 years already

**Comment by radare** [comment]
maybe i will set it up again one day, but i have no time and this is pretty low in my priority list, anyone can do that if they want, all the code is public
