### ISSUE TITLE
Download urls incorrect

### ISSUE THREAD

**Issue by KOLANICH** [radare/radare.org#24]
also site reports that latest is 0.9.8 but I have found 0.9.9 in http://radare.org/get/pkg/

**Comment by jvoisin** [comment]
It'll be the next release, it's not out yet.

**Comment by radare** [comment]
0.9.9 are nightly builds from git. Those are not stable or released at all. Just for testing. Release will happen in february, ill update all links then

**Comment by KOLANICH** [comment]
links to 0.9.8 are also incorrect

**Comment by radare** [comment]
Please, try again, i have fixed them
thanks!
