### ISSUE TITLE
Windows Download is broken

### ISSUE THREAD

**Issue by JanWerder** [radare/radare.org#26]
http://www.radare.org/get/pkg/radare2-w32-0.9.8git.zip
is not available for me

**Comment by XVilka** [comment]
@JanWerder http://bin.rada.re/ - see here (nightly builds).
But yes, shall be fixed. Thank you!

**Comment by radare** [comment]
where did you get that link from? the link in the web page is correct

**Comment by XVilka** [comment]
@radare http://radare.org/get/pkg/radare2-w32-0.9.9-git.zip - this one contains broken (on windows) radare2, pls use http://bin.rada.re/radare2-w32-0.9.9-git.zip (it does work)

**Comment by radare** [comment]
Already fixed

**Comment by JanWerder** [comment]
not fixed

![](http://i.imgur.com/nbkAINS.jpg)

**Comment by JanWerder** [comment]
1. Same on the http://www.radare.org/r/down.html page
2. Version number on http://www.radare.org/r/down.html is wrong

**Comment by radare** [comment]
I have replaced the zip in get/pkg with the one from bin.rada.re

**Comment by radare** [comment]
So it was already fixed. Am i missing anything?

**Comment by JanWerder** [comment]
only the "last release is 0.9.8" text on http://www.radare.org/r/down.html.

**Comment by radare** [comment]
The last release is 0.9.8, but the windows build for 0.9.9 is way better for windows. There are tons of bugs fixed for this platform. I will release it soon. So that will be updated acoordingly. Meanwhile keep using that zip :)
