### ISSUE TITLE
hack.lu 2015

### ISSUE THREAD

**Issue by Maijin** [radare/radare.org#35]
https://github.com/radare/radare.org/commit/3f9e01840d53043e60f404aba2db8480b08aff93

PDF1: http://rghost.net/private/7bgHBM4Tx/4bbf4cbc849975bc7a57b4c1e4414b2e

PDF2: http://rghost.net/private/87kj7C54S/211b5d10ff124664563bc38b1e370c1e

**Comment by radare** [comment]
This is not a PR

**Comment by radare** [comment]
we were discussing about commiting the slides in git too. the only problem i see on this is the videos or audios which are bigger.

**Comment by radare** [comment]
I just downloaded them into /get... i'll push all the slides in a commit later this week
