### ISSUE TITLE
Using http://bin.rada.re/ with radare2 for Android?

### ISSUE THREAD

**Issue by Manouchehri** [radare/radare.org#38]
The [installer](https://play.google.com/store/apps/details?id=org.radare2.installer&hl=en) doesn't seem to be able to grab nightly binaries off http://bin.rada.re/, it's expecting `<base_url>/aarch64/unstable` or `<base_url>/aarch64/unstable`.

The builds on `http://radare.org/get/pkg/android/aarch64/` seem to be a few months out of date.

**Comment by radare** [comment]
This issue should be filled in the radare2-installer repo which is where the source of the android app lives

**Comment by Manouchehri** [comment]
Done. https://github.com/radare/radare2-installer/issues/8
