### ISSUE TITLE
Download URLs outdated or dead

### ISSUE THREAD

**Issue by makigumo** [radare/radare.org#44]
There are problems with the download links at http://www.radare.org/r/down.html

* radare2     1.0     2016-11-09 should be updated to 1.0.2
* bindings    1.0     2016-11-09 should be updated to 1.0.1
* r2pipe      1.0     2016-11-09 is a dead link
* r2-extras   1.0     2016-11-09 is a dead link

regards

**Comment by Maijin** [comment]
What about PR instead ?

**Comment by makigumo** [comment]
I would, but I'm not sure what to do.
* [/r/web.config](https://github.com/radare/radare.org/blob/master/r/web.config) looks current, so `radare2` and `bindings` should already point to the latest versions. Maybe a webpage rebuild is required?
* That still leaves the dead links, because the files are missing from `http://www.radare.org/get/`. 
    * Were there ever any `r2pipe` packages released? Couldn't find any in `/get`
    * a package of `radare2-extras-1.0.tar.xz` needs to be uploaded to `/get`, currently the latest is still `http://www.radare.org/get/radare2-extras-0.10.6.tar.xz`.

**Comment by radare** [comment]
Thanks. I need better release scripts to automate this, handwork is tedious and may fail
